# Site settings
title: bone-stew blog
subtitle:
SEOTitle: bone-stew blog
header-img: img/home-bg.jpg
email: dyffh1031@gmail.com
description: "bone-stew 개발 블로그"
keyword: "bone-stew, IT&E, KOSA, 7기"
url: "https://bone-stew.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: huxpro
#zhihu_username: huxpro
github_username: bone-stew
#twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username:

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "" # Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "team bone-stew"
sidebar-avatar: https://avatars.githubusercontent.com/u/141702188?s=400&u=484a5f194e575170c3790aec5b6fd03c0cc8f958&v=4 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "김우원", href: "https://github.com/WoowonKim" },
    { title: "서명현", href: "https://github.com/sa46lll" },
    { title: "조재룡", href: "https://github.com/jae-ryong" },
    { title: "조상원", href: "https://github.com/swc617" },
  ]
